name: taskbuddy
description: "A minimal Todo application created using Flutter 💙"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  hive_flutter: ^1.1.0
  hive:
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator:
  build_runner:
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
     - assets/images/man.png
     - assets/images/woman.png
     - assets/images/logo.png
     - assets/images/send.png
  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SF-Pro.otf
